-- Add test jobs for schedule functionality
-- This script adds sample jobs with dates and times for testing

INSERT INTO job_cards (
    job_number,
    job_date,
    start_time,
    end_time,
    status,
    job_type,
    job_description,
    priority,
    customer_name,
    customer_email,
    customer_phone,
    vehicle_registration,
    vehicle_make,
    vehicle_model,
    technician_name,
    technician_phone, -- This contains the email address
    job_location,
    estimated_duration_hours,
    created_at
) VALUES 
-- Today's jobs
(
    'JC-20241201-0001',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '9 hours',
    CURRENT_DATE + INTERVAL '11 hours',
    'pending',
    'install',
    'Install GPS tracking device on delivery truck',
    'high',
    'ABC Transport Ltd',
    'contact@abctransport.com',
    '+27 11 123 4567',
    'ABC123GP',
    'Mercedes',
    'Sprinter',
    'John Smith',
    'john.smith@company.com',
    '123 Main Street, Johannesburg',
    2,
    NOW()
),
(
    'JC-20241201-0002',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '14 hours',
    CURRENT_DATE + INTERVAL '16 hours',
    'pending',
    'maintenance',
    'Maintenance check on fleet vehicle',
    'medium',
    'XYZ Logistics',
    'info@xyzlogistics.co.za',
    '+27 11 987 6543',
    'XYZ789GP',
    'Ford',
    'Transit',
    'Sarah Johnson',
    'sarah.johnson@company.com',
    '456 Business Park, Pretoria',
    2,
    NOW()
),
-- Tomorrow's jobs
(
    'JC-20241201-0003',
    CURRENT_DATE + INTERVAL '1 day',
    CURRENT_DATE + INTERVAL '1 day' + INTERVAL '10 hours',
    CURRENT_DATE + INTERVAL '1 day' + INTERVAL '12 hours',
    'pending',
    'install',
    'Install security system on warehouse',
    'urgent',
    'Secure Storage Co',
    'admin@securestorage.co.za',
    '+27 11 555 1234',
    'SEC456GP',
    'Toyota',
    'Hilux',
    'Mike Wilson',
    'mike.wilson@company.com',
    '789 Industrial Area, Cape Town',
    2,
    NOW()
),
(
    'JC-20241201-0004',
    CURRENT_DATE + INTERVAL '1 day',
    CURRENT_DATE + INTERVAL '1 day' + INTERVAL '13 hours',
    CURRENT_DATE + INTERVAL '1 day' + INTERVAL '15 hours',
    'pending',
    'repair',
    'Repair GPS unit on service vehicle',
    'high',
    'City Services',
    'services@cityservices.gov.za',
    '+27 11 777 8888',
    'CITY001GP',
    'Nissan',
    'Navara',
    'Lisa Brown',
    'lisa.brown@company.com',
    '321 Service Road, Durban',
    2,
    NOW()
),
-- Next week's jobs
(
    'JC-20241201-0005',
    CURRENT_DATE + INTERVAL '7 days',
    CURRENT_DATE + INTERVAL '7 days' + INTERVAL '8 hours',
    CURRENT_DATE + INTERVAL '7 days' + INTERVAL '10 hours',
    'pending',
    'deinstall',
    'Remove old tracking system',
    'medium',
    'Old Fleet Ltd',
    'fleet@oldfleet.co.za',
    '+27 11 444 5555',
    'OLD123GP',
    'Volkswagen',
    'Crafter',
    'David Lee',
    'david.lee@company.com',
    '654 Old Street, Port Elizabeth',
    2,
    NOW()
),
(
    'JC-20241201-0006',
    CURRENT_DATE + INTERVAL '7 days',
    CURRENT_DATE + INTERVAL '7 days' + INTERVAL '11 hours',
    CURRENT_DATE + INTERVAL '7 days' + INTERVAL '13 hours',
    'pending',
    'install',
    'Install new tracking system',
    'high',
    'New Fleet Ltd',
    'fleet@newfleet.co.za',
    '+27 11 666 7777',
    'NEW456GP',
    'Iveco',
    'Daily',
    'Emma Davis',
    'emma.davis@company.com',
    '987 New Street, Bloemfontein',
    2,
    NOW()
),
-- Jobs with different statuses
(
    'JC-20241201-0007',
    CURRENT_DATE - INTERVAL '1 day',
    CURRENT_DATE - INTERVAL '1 day' + INTERVAL '9 hours',
    CURRENT_DATE - INTERVAL '1 day' + INTERVAL '11 hours',
    'completed',
    'install',
    'Install tracking system on delivery van',
    'high',
    'Fast Delivery',
    'delivery@fastdelivery.co.za',
    '+27 11 111 2222',
    'FAST001GP',
    'Peugeot',
    'Partner',
    'Tom Anderson',
    'tom.anderson@company.com',
    '111 Delivery Street, Johannesburg',
    2,
    NOW()
),
(
    'JC-20241201-0008',
    CURRENT_DATE + INTERVAL '2 days',
    CURRENT_DATE + INTERVAL '2 days' + INTERVAL '14 hours',
    CURRENT_DATE + INTERVAL '2 days' + INTERVAL '16 hours',
    'in_progress',
    'maintenance',
    'Regular maintenance check',
    'medium',
    'Reliable Transport',
    'maintenance@reliabletransport.co.za',
    '+27 11 333 4444',
    'REL789GP',
    'Isuzu',
    'N-Series',
    'Anna White',
    'anna.white@company.com',
    '222 Maintenance Road, Pretoria',
    2,
    NOW()
);

-- Update the created_at timestamp to be more realistic
UPDATE job_cards 
SET created_at = NOW() - INTERVAL '1 day'
WHERE job_number LIKE 'JC-20241201-%';
