create table public.inventory_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  category_code text not null,
  serial_number text not null,
  date_adjusted date null,
  container text null,
  direction text null,
  status text not null default 'AVAILABLE',
  assigned_to_technician text null,
  assigned_date timestamp with time zone null,
  job_card_id bigint null,
  company text null,
  notes text null,
  constraint inventory_items_pkey primary key (id),
  constraint inventory_items_category_code_fkey foreign key (category_code) references inventory_categories (code) on delete cascade,
  constraint inventory_items_serial_number_key unique (serial_number)
) TABLESPACE pg_default;