-- Create new vehicles table structure
CREATE TABLE public.vehicles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  company text null,
  new_account_number text null,
  branch text null,
  unique_id uuid null default gen_random_uuid(),
  fleet_number text null,
  reg text null,
  controlroom text null,
  total_rental_sub numeric(10, 2) null,
  total_rental numeric(10, 2) null,
  total_sub numeric(10, 2) null,
  constraint vehicles_pkey primary key (id)
) TABLESPACE pg_default;

-- Add indexes for better performance
CREATE INDEX idx_vehicles_account_number ON public.vehicles(new_account_number);
CREATE INDEX idx_vehicles_company ON public.vehicles(company);
CREATE INDEX idx_vehicles_reg ON public.vehicles(reg);
CREATE INDEX idx_vehicles_fleet_number ON public.vehicles(fleet_number);

-- Add comments for clarity
COMMENT ON TABLE public.vehicles IS 'Vehicle inventory and billing information';
COMMENT ON COLUMN public.vehicles.company IS 'Company name';
COMMENT ON COLUMN public.vehicles.new_account_number IS 'Account number for billing';
COMMENT ON COLUMN public.vehicles.reg IS 'Vehicle registration number';
COMMENT ON COLUMN public.vehicles.fleet_number IS 'Fleet number if no registration';
COMMENT ON COLUMN public.vehicles.total_rental IS 'Rental amount (if applicable)';
COMMENT ON COLUMN public.vehicles.total_sub IS 'Subscription amount (if applicable)';
COMMENT ON COLUMN public.vehicles.total_rental_sub IS 'Combined rental + subscription amount';
