-- Create inventory categories table
CREATE TABLE public.inventory_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  code text NOT NULL,
  description text NOT NULL,
  total_count integer DEFAULT 0,
  date_adjusted date,
  company text,
  CONSTRAINT inventory_categories_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_categories_code_key UNIQUE (code)
) TABLESPACE pg_default;

-- Create inventory items table
CREATE TABLE public.inventory_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category_code text NOT NULL,
  serial_number text NOT NULL,
  date_adjusted date,
  container text,
  direction text,
  status text DEFAULT 'IN STOCK',
  company text,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_serial_key UNIQUE (serial_number),
  CONSTRAINT inventory_items_category_fkey FOREIGN KEY (category_code) REFERENCES public.inventory_categories(code)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE public.inventory_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view inventory categories" ON public.inventory_categories
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage inventory categories" ON public.inventory_categories
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Users can view inventory items" ON public.inventory_items
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Users can manage inventory items" ON public.inventory_items
  FOR ALL USING (auth.role() = 'authenticated');