-- Note: Using existing 'invoices' bucket for job photos
-- The following policies should already exist for the invoices bucket
-- If you need to add specific policies for job photos, you can modify the existing ones

-- Example: If you want to ensure authenticated users can upload job photos to invoices bucket
-- CREATE POLICY "Allow authenticated users to upload job photos to invoices" ON storage.objects
-- FOR INSERT WITH CHECK (
--   bucket_id = 'invoices' 
--   AND auth.role() = 'authenticated'
--   AND (storage.foldername(name))[1] = 'before_photos'
-- );
