-- Client stock tables that mirror the soltrack inventory model.
-- Parent catalog remains public.inventory_categories via category_code.

CREATE TABLE IF NOT EXISTS public.client_inventory_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_code text NOT NULL,
  cost_code text NOT NULL,
  category_code text NOT NULL,
  total_count integer NULL DEFAULT 0,
  date_adjusted date NULL,
  company text NULL,
  CONSTRAINT client_inventory_categories_pkey PRIMARY KEY (id),
  CONSTRAINT client_inventory_categories_unique UNIQUE (client_code, cost_code, category_code),
  CONSTRAINT client_inventory_categories_category_fkey
    FOREIGN KEY (category_code)
    REFERENCES public.inventory_categories (code)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.client_inventory_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_code text NOT NULL,
  cost_code text NOT NULL,
  category_code text NOT NULL,
  serial_number text NOT NULL,
  date_adjusted date NULL,
  container text NULL,
  direction text NULL,
  status text NULL DEFAULT 'IN STOCK'::text,
  assigned_to_technician text NULL,
  assigned_date timestamp with time zone NULL,
  job_card_id uuid NULL,
  company text NULL,
  notes text NULL,
  CONSTRAINT client_inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT client_inventory_items_client_serial_unique UNIQUE (client_code, cost_code, serial_number),
  CONSTRAINT client_inventory_items_client_category_fkey
    FOREIGN KEY (client_code, cost_code, category_code)
    REFERENCES public.client_inventory_categories (client_code, cost_code, category_code)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT client_inventory_items_category_fkey
    FOREIGN KEY (category_code)
    REFERENCES public.inventory_categories (code)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT client_inventory_items_job_card_fkey
    FOREIGN KEY (job_card_id)
    REFERENCES public.job_cards (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_client_inventory_categories_client_code
  ON public.client_inventory_categories (client_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_categories_cost_code
  ON public.client_inventory_categories (cost_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_categories_category_code
  ON public.client_inventory_categories (category_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_items_client_code
  ON public.client_inventory_items (client_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_items_cost_code
  ON public.client_inventory_items (cost_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_items_category_code
  ON public.client_inventory_items (category_code);

CREATE INDEX IF NOT EXISTS idx_client_inventory_items_status
  ON public.client_inventory_items (status);

CREATE INDEX IF NOT EXISTS idx_client_inventory_items_job_card_id
  ON public.client_inventory_items (job_card_id);

CREATE OR REPLACE FUNCTION public.recalc_client_inventory_total(
  p_client_code text,
  p_cost_code text,
  p_category_code text
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.client_inventory_categories cic
  SET
    total_count = (
      SELECT COUNT(*)
      FROM public.client_inventory_items cii
      WHERE cii.client_code = p_client_code
        AND cii.cost_code = p_cost_code
        AND cii.category_code = p_category_code
        AND cii.status = 'IN STOCK'
    ),
    date_adjusted = CURRENT_DATE
  WHERE cic.client_code = p_client_code
    AND cic.cost_code = p_cost_code
    AND cic.category_code = p_category_code;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_client_inventory_category_totals()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.recalc_client_inventory_total(NEW.client_code, NEW.cost_code, NEW.category_code);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD.client_code IS DISTINCT FROM NEW.client_code
       OR OLD.cost_code IS DISTINCT FROM NEW.cost_code
       OR OLD.category_code IS DISTINCT FROM NEW.category_code THEN
      PERFORM public.recalc_client_inventory_total(OLD.client_code, OLD.cost_code, OLD.category_code);
    END IF;

    PERFORM public.recalc_client_inventory_total(NEW.client_code, NEW.cost_code, NEW.category_code);
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    PERFORM public.recalc_client_inventory_total(OLD.client_code, OLD.cost_code, OLD.category_code);
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_client_inventory_category_totals
  ON public.client_inventory_items;

CREATE TRIGGER trg_sync_client_inventory_category_totals
AFTER INSERT OR UPDATE OR DELETE ON public.client_inventory_items
FOR EACH ROW
EXECUTE FUNCTION public.sync_client_inventory_category_totals();

COMMENT ON TABLE public.client_inventory_categories IS
'Client-level stock buckets. Each row is a client code + cost code + parent inventory category code.';

COMMENT ON TABLE public.client_inventory_items IS
'Serialized or tracked client stock items, scoped by client code and cost code, linked to parent inventory_categories.';
