-- ============================================================
-- Migration: DB-Level Stock Movement Audit Trail
-- ============================================================
-- Creates a stock_movements table and 4 triggers that log
-- every stock change across all 4 buckets:
--   1. inventory_items (Soltrack central stock)
--   2. client_inventory_items (Client-level stock)
--   3. tech_stock (Technician boot stock - assigned_parts)
--   4. job_cards (parts_required + equipment_used)
--
-- Zero app code changes. Pure database triggers.
-- Search by serial_number to see the full journey of any part.
-- ============================================================

-- ============================================================
-- 1. TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  serial_number text NOT NULL,
  category_code text,
  operation text NOT NULL,
  from_bucket text,
  to_bucket text,
  from_owner text,
  to_owner text,
  from_field text,
  to_field text,
  client_code text,
  cost_code text,
  job_card_id uuid,
  job_number text,
  quantity integer DEFAULT 1,
  old_status text,
  new_status text,
  old_assigned_to text,
  new_assigned_to text,
  old_data jsonb,
  new_data jsonb,
  diff jsonb,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id)
);

-- ============================================================
-- 2. INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_stock_movements_serial
  ON public.stock_movements (serial_number);

CREATE INDEX IF NOT EXISTS idx_stock_movements_job_card
  ON public.stock_movements (job_card_id);

CREATE INDEX IF NOT EXISTS idx_stock_movements_from_bucket
  ON public.stock_movements (from_bucket);

CREATE INDEX IF NOT EXISTS idx_stock_movements_to_bucket
  ON public.stock_movements (to_bucket);

CREATE INDEX IF NOT EXISTS idx_stock_movements_from_owner
  ON public.stock_movements (from_owner);

CREATE INDEX IF NOT EXISTS idx_stock_movements_to_owner
  ON public.stock_movements (to_owner);

CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at
  ON public.stock_movements (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_movements_operation
  ON public.stock_movements (operation);

-- ============================================================
-- 3. TRIGGER FUNCTIONS
-- ============================================================

-- ----------------------------------------------------------
-- 3a. inventory_items trigger
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_inventory_items_movement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_from_bucket text;
  v_to_bucket text;
  v_from_owner text;
  v_to_owner text;
  v_job_number text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_to_bucket := 'soltrack';

    IF NEW.assigned_to_technician IS NOT NULL THEN
      v_to_bucket := 'tech';
      v_to_owner := NEW.assigned_to_technician;
    END IF;

    IF NEW.job_card_id IS NOT NULL THEN
      v_to_bucket := 'job';
      SELECT jc.job_number INTO v_job_number
      FROM public.job_cards jc WHERE jc.id = NEW.job_card_id;
    END IF;

    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket, to_owner,
      job_card_id, job_number,
      new_status, new_assigned_to, new_data
    ) VALUES (
      NEW.serial_number, NEW.category_code, 'INSERT',
      NULL, v_to_bucket, v_to_owner,
      NEW.job_card_id, v_job_number,
      NEW.status, NEW.assigned_to_technician, to_jsonb(NEW)
    );

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD.status IS DISTINCT FROM NEW.status
       OR OLD.assigned_to_technician IS DISTINCT FROM NEW.assigned_to_technician
       OR OLD.job_card_id IS DISTINCT FROM NEW.job_card_id THEN

      v_from_bucket := 'soltrack';
      v_to_bucket := 'soltrack';

      IF OLD.assigned_to_technician IS DISTINCT FROM NEW.assigned_to_technician THEN
        IF NEW.assigned_to_technician IS NOT NULL THEN
          v_to_bucket := 'tech';
          v_to_owner := NEW.assigned_to_technician;
        ELSE
          v_from_bucket := 'tech';
          v_from_owner := OLD.assigned_to_technician;
        END IF;
      END IF;

      IF OLD.job_card_id IS DISTINCT FROM NEW.job_card_id THEN
        IF NEW.job_card_id IS NOT NULL THEN
          v_to_bucket := 'job';
          SELECT jc.job_number INTO v_job_number
          FROM public.job_cards jc WHERE jc.id = NEW.job_card_id;
        ELSE
          v_from_bucket := 'job';
        END IF;
      END IF;

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, from_owner, to_owner,
        job_card_id, job_number,
        old_status, new_status,
        old_assigned_to, new_assigned_to,
        old_data, new_data
      ) VALUES (
        NEW.serial_number, NEW.category_code, 'UPDATE',
        v_from_bucket, v_to_bucket, v_from_owner, v_to_owner,
        NEW.job_card_id, v_job_number,
        OLD.status, NEW.status,
        OLD.assigned_to_technician, NEW.assigned_to_technician,
        to_jsonb(OLD), to_jsonb(NEW)
      );
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket,
      old_status, old_assigned_to, old_data
    ) VALUES (
      OLD.serial_number, OLD.category_code, 'DELETE',
      'soltrack', NULL,
      OLD.status, OLD.assigned_to_technician, to_jsonb(OLD)
    );

    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;

-- ----------------------------------------------------------
-- 3b. client_inventory_items trigger
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_client_inventory_items_movement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_from_bucket text;
  v_to_bucket text;
  v_from_owner text;
  v_to_owner text;
  v_job_number text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_to_bucket := 'client';
    v_to_owner := NEW.client_code;

    IF NEW.assigned_to_technician IS NOT NULL THEN
      v_to_bucket := 'tech';
      v_to_owner := NEW.assigned_to_technician;
    END IF;

    IF NEW.job_card_id IS NOT NULL THEN
      v_to_bucket := 'job';
      SELECT jc.job_number INTO v_job_number
      FROM public.job_cards jc WHERE jc.id = NEW.job_card_id;
    END IF;

    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket, to_owner,
      client_code, cost_code,
      job_card_id, job_number,
      new_status, new_assigned_to, new_data
    ) VALUES (
      NEW.serial_number, NEW.category_code, 'INSERT',
      NULL, v_to_bucket, v_to_owner,
      NEW.client_code, NEW.cost_code,
      NEW.job_card_id, v_job_number,
      NEW.status, NEW.assigned_to_technician, to_jsonb(NEW)
    );

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD.status IS DISTINCT FROM NEW.status
       OR OLD.assigned_to_technician IS DISTINCT FROM NEW.assigned_to_technician
       OR OLD.job_card_id IS DISTINCT FROM NEW.job_card_id THEN

      v_from_bucket := 'client';
      v_from_owner := OLD.client_code;
      v_to_bucket := 'client';
      v_to_owner := NEW.client_code;

      IF OLD.assigned_to_technician IS DISTINCT FROM NEW.assigned_to_technician THEN
        IF NEW.assigned_to_technician IS NOT NULL THEN
          v_to_bucket := 'tech';
          v_to_owner := NEW.assigned_to_technician;
        ELSE
          v_from_bucket := 'tech';
          v_from_owner := OLD.assigned_to_technician;
          v_to_bucket := 'client';
          v_to_owner := NEW.client_code;
        END IF;
      END IF;

      IF OLD.job_card_id IS DISTINCT FROM NEW.job_card_id THEN
        IF NEW.job_card_id IS NOT NULL THEN
          v_to_bucket := 'job';
          SELECT jc.job_number INTO v_job_number
          FROM public.job_cards jc WHERE jc.id = NEW.job_card_id;
        ELSE
          v_from_bucket := 'job';
          v_to_bucket := 'client';
          v_to_owner := NEW.client_code;
        END IF;
      END IF;

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, from_owner, to_owner,
        client_code, cost_code,
        job_card_id, job_number,
        old_status, new_status,
        old_assigned_to, new_assigned_to,
        old_data, new_data
      ) VALUES (
        NEW.serial_number, NEW.category_code, 'UPDATE',
        v_from_bucket, v_to_bucket, v_from_owner, v_to_owner,
        NEW.client_code, NEW.cost_code,
        NEW.job_card_id, v_job_number,
        OLD.status, NEW.status,
        OLD.assigned_to_technician, NEW.assigned_to_technician,
        to_jsonb(OLD), to_jsonb(NEW)
      );
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket,
      client_code, cost_code,
      old_status, old_assigned_to, old_data
    ) VALUES (
      OLD.serial_number, OLD.category_code, 'DELETE',
      'client', NULL,
      OLD.client_code, OLD.cost_code,
      OLD.status, OLD.assigned_to_technician, to_jsonb(OLD)
    );

    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;

-- ----------------------------------------------------------
-- 3c. tech_stock trigger (diffs assigned_parts array)
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_tech_stock_movement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_item jsonb;
  v_serial text;
BEGIN
  IF OLD.assigned_parts IS NOT DISTINCT FROM NEW.assigned_parts THEN
    RETURN NEW;
  END IF;

  -- Parts REMOVED from assigned_parts (went somewhere)
  FOR v_serial, v_item IN
    SELECT item->>'serial_number', item
    FROM jsonb_array_elements(COALESCE(OLD.assigned_parts, '[]'::jsonb)) AS item
    WHERE NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(COALESCE(NEW.assigned_parts, '[]'::jsonb)) AS n
      WHERE n->>'serial_number' = item->>'serial_number'
    )
  LOOP
    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket, from_owner,
      old_data, new_data, diff
    ) VALUES (
      v_serial,
      v_item->>'category_code',
      'PART_REMOVED',
      'tech',
      NULL,
      OLD.technician_email,
      jsonb_build_object('assigned_parts', OLD.assigned_parts),
      jsonb_build_object('assigned_parts', NEW.assigned_parts),
      jsonb_build_object('removed', jsonb_build_array(v_item))
    );
  END LOOP;

  -- Parts ADDED to assigned_parts (came from somewhere)
  FOR v_serial, v_item IN
    SELECT item->>'serial_number', item
    FROM jsonb_array_elements(COALESCE(NEW.assigned_parts, '[]'::jsonb)) AS item
    WHERE NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(COALESCE(OLD.assigned_parts, '[]'::jsonb)) AS o
      WHERE o->>'serial_number' = item->>'serial_number'
    )
  LOOP
    INSERT INTO public.stock_movements (
      serial_number, category_code, operation,
      from_bucket, to_bucket, to_owner,
      old_data, new_data, diff
    ) VALUES (
      v_serial,
      v_item->>'category_code',
      'PART_ADDED',
      NULL,
      'tech',
      NEW.technician_email,
      jsonb_build_object('assigned_parts', OLD.assigned_parts),
      jsonb_build_object('assigned_parts', NEW.assigned_parts),
      jsonb_build_object('added', jsonb_build_array(v_item))
    );
  END LOOP;

  RETURN NEW;
END;
$$;

-- ----------------------------------------------------------
-- 3d. job_cards trigger (diffs parts_required + equipment_used)
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.log_job_cards_stock_movement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_item jsonb;
  v_serial text;
  v_source text;
  v_from_bucket text;
BEGIN
  -- ========================================================
  -- parts_required changes
  -- ========================================================
  IF OLD.parts_required IS DISTINCT FROM NEW.parts_required THEN

    -- Removed from parts_required
    FOR v_serial, v_item IN
      SELECT item->>'serial_number', item
      FROM jsonb_array_elements(COALESCE(OLD.parts_required, '[]'::jsonb)) AS item
      WHERE NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE(NEW.parts_required, '[]'::jsonb)) AS n
        WHERE n->>'serial_number' = item->>'serial_number'
      )
    LOOP
      v_source := v_item->>'source';

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, from_field,
        job_card_id, job_number,
        old_data, new_data
      ) VALUES (
        v_serial,
        v_item->>'category_code',
        'PART_REMOVED_FROM_PARTS_REQUIRED',
        'job',
        CASE
          WHEN v_source = 'tech_stock.assigned_parts' THEN 'tech'
          WHEN v_source = 'inventory_items' THEN 'soltrack'
          WHEN v_source LIKE 'client_inventory_items%' THEN 'client'
          ELSE NULL
        END,
        'parts_required',
        NEW.id,
        NEW.job_number,
        jsonb_build_object('parts_required', OLD.parts_required),
        jsonb_build_object('parts_required', NEW.parts_required)
      );
    END LOOP;

    -- Added to parts_required
    FOR v_serial, v_item IN
      SELECT item->>'serial_number', item
      FROM jsonb_array_elements(COALESCE(NEW.parts_required, '[]'::jsonb)) AS item
      WHERE NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE(OLD.parts_required, '[]'::jsonb)) AS o
        WHERE o->>'serial_number' = item->>'serial_number'
      )
    LOOP
      v_source := v_item->>'source';

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, to_field,
        job_card_id, job_number,
        old_data, new_data
      ) VALUES (
        v_serial,
        v_item->>'category_code',
        'PART_ADDED_TO_PARTS_REQUIRED',
        CASE
          WHEN v_source = 'tech_stock.assigned_parts' THEN 'tech'
          WHEN v_source = 'inventory_items' THEN 'soltrack'
          WHEN v_source LIKE 'client_inventory_items%' THEN 'client'
          ELSE NULL
        END,
        'job',
        'parts_required',
        NEW.id,
        NEW.job_number,
        jsonb_build_object('parts_required', OLD.parts_required),
        jsonb_build_object('parts_required', NEW.parts_required)
      );
    END LOOP;
  END IF;

  -- ========================================================
  -- equipment_used changes
  -- ========================================================
  IF OLD.equipment_used IS DISTINCT FROM NEW.equipment_used THEN

    -- Removed from equipment_used
    FOR v_serial, v_item IN
      SELECT item->>'serial_number', item
      FROM jsonb_array_elements(COALESCE(OLD.equipment_used, '[]'::jsonb)) AS item
      WHERE NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE(NEW.equipment_used, '[]'::jsonb)) AS n
        WHERE n->>'serial_number' = item->>'serial_number'
      )
    LOOP
      v_source := v_item->>'source';

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, from_field, from_owner,
        job_card_id, job_number,
        old_data, new_data
      ) VALUES (
        v_serial,
        v_item->>'category_code',
        'PART_REMOVED_FROM_EQUIPMENT_USED',
        'job',
        CASE
          WHEN v_source = 'tech_stock.assigned_parts' THEN 'tech'
          WHEN v_source = 'inventory_items' THEN 'soltrack'
          WHEN v_source LIKE 'client_inventory_items%' THEN 'client'
          ELSE NULL
        END,
        'equipment_used',
        v_item->>'technician_email',
        NEW.id,
        NEW.job_number,
        jsonb_build_object('equipment_used', OLD.equipment_used),
        jsonb_build_object('equipment_used', NEW.equipment_used)
      );
    END LOOP;

    -- Added to equipment_used
    FOR v_serial, v_item IN
      SELECT item->>'serial_number', item
      FROM jsonb_array_elements(COALESCE(NEW.equipment_used, '[]'::jsonb)) AS item
      WHERE NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(COALESCE(OLD.equipment_used, '[]'::jsonb)) AS o
        WHERE o->>'serial_number' = item->>'serial_number'
      )
    LOOP
      v_source := v_item->>'source';

      INSERT INTO public.stock_movements (
        serial_number, category_code, operation,
        from_bucket, to_bucket, to_field, to_owner,
        job_card_id, job_number,
        old_data, new_data
      ) VALUES (
        v_serial,
        v_item->>'category_code',
        'PART_ADDED_TO_EQUIPMENT_USED',
        CASE
          WHEN v_source = 'tech_stock.assigned_parts' THEN 'tech'
          WHEN v_source = 'inventory_items' THEN 'soltrack'
          WHEN v_source LIKE 'client_inventory_items%' THEN 'client'
          ELSE NULL
        END,
        'job',
        'equipment_used',
        v_item->>'technician_email',
        NEW.id,
        NEW.job_number,
        jsonb_build_object('equipment_used', OLD.equipment_used),
        jsonb_build_object('equipment_used', NEW.equipment_used)
      );
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$;

-- ============================================================
-- 4. TRIGGERS
-- ============================================================

CREATE TRIGGER trg_log_inventory_items_movement
  AFTER INSERT OR UPDATE OR DELETE ON public.inventory_items
  FOR EACH ROW
  EXECUTE FUNCTION public.log_inventory_items_movement();

CREATE TRIGGER trg_log_client_inventory_items_movement
  AFTER INSERT OR UPDATE OR DELETE ON public.client_inventory_items
  FOR EACH ROW
  EXECUTE FUNCTION public.log_client_inventory_items_movement();

CREATE TRIGGER trg_log_tech_stock_movement
  AFTER UPDATE ON public.tech_stock
  FOR EACH ROW
  WHEN (OLD.assigned_parts IS DISTINCT FROM NEW.assigned_parts)
  EXECUTE FUNCTION public.log_tech_stock_movement();

CREATE TRIGGER trg_log_job_cards_stock_movement
  AFTER UPDATE ON public.job_cards
  FOR EACH ROW
  WHEN (OLD.parts_required IS DISTINCT FROM NEW.parts_required
        OR OLD.equipment_used IS DISTINCT FROM NEW.equipment_used)
  EXECUTE FUNCTION public.log_job_cards_stock_movement();
